openapi: 3.0.3
info:
  title: ODIN Secure Communication API
  version: 1.0.0
servers:
  - url: https://odin-gateway-583712448463.us-central1.run.app
components:
  securitySchemes:
    googleIdToken:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /health:
    get:
      security: [{ googleIdToken: [] }]
      responses:
        '200': { description: OK }
  /.well-known/odin/discovery.json:
    get:
      security: [{ googleIdToken: [] }]
      responses: { '200': { description: Discovery } }
  /.well-known/jwks.json:
    get:
      security: [{ googleIdToken: [] }]
      responses: { '200': { description: JWKS } }
  /v1/envelope:
    post:
      security: [{ googleIdToken: [] }]
      parameters:
        - in: header
          name: X-ODIN-Trace-Id
          required: true
          schema: { type: string }
        - in: header
          name: X-ODIN-Payload-CID
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { type: object }
            example: { payload: { smoke: true } }
      responses:
        '201':
          description: Created
  /v1/receipts/hops:
    get:
      security: [{ googleIdToken: [] }]
      parameters:
        - in: query
          name: trace_id
          required: true
          schema: { type: string }
      responses: { '200': { description: Hop list } }
  /v1/receipts/hops/chain/{trace_id}:
    get:
      security: [{ googleIdToken: [] }]
      parameters:
        - in: path
          name: trace_id
          required: true
          schema: { type: string }
      responses: { '200': { description: Chain list } }
